import { TicketingEvent } from "../types";

export const mockTicketingEvents: TicketingEvent[] = [
  {
    id: "1",
    title: "Rapperholic Concert 2024",
    eventCode: "RAP24",
    category: "Concert",
    image: "https://picsum.photos/seed/rapper/800/600",
    date: "Dec 25, 2024",
    time: "8:00 PM",
    status: "Upcoming",
    organizer: "SarkCess Music",
    description: "The annual shutdown concert by King Sark.",
    venue: "Grand Arena, AICC",
    ticketTypes: [
      {
        id: "t_reg",
        name: "Regular",
        price: 200,
        available: 500,
        description: "Standard entry",
      },
      {
        id: "t_vip",
        name: "VIP",
        price: 500,
        available: 100,
        description: "Front row access + drinks",
      },
    ],
  },
  {
    id: "2",
    title: "Tech In Ghana Conference",
    eventCode: "TIG25",
    category: "School", // Using existing union type, though 'Conference' might be better later
    image: "https://picsum.photos/seed/techconf/800/600",
    date: "Jan 15, 2025",
    time: "9:00 AM",
    status: "Upcoming",
    organizer: "Tech Ghana Network",
    description: "Connecting the Ghanaian tech ecosystem.",
    venue: "Kempinski Hotel",
    ticketTypes: [
      {
        id: "t_early",
        name: "Early Bird",
        price: 150,
        available: 50,
      },
      {
        id: "t_stand",
        name: "Standard",
        price: 300,
        available: 200,
      },
    ],
  },
  {
    id: "3",
    title: "Hearts of Oak vs Asante Kotoko",
    eventCode: "SUPERCLASH",
    category: "Sports",
    image: "https://picsum.photos/seed/football/800/600",
    date: "Feb 14, 2025",
    time: "3:00 PM",
    status: "Upcoming",
    organizer: "GFA",
    description: "The biggest football rivalry in Ghana.",
    venue: "Accra Sports Stadium",
    ticketTypes: [
      {
        id: "t_pop",
        name: "Popular Stand",
        price: 50,
        available: 1000,
      },
      {
        id: "t_vip",
        name: "VIP",
        price: 200,
        available: 200,
      },
    ],
  },
  {
    id: "4",
    title: "The Legend of Aku Sika",
    eventCode: "AKUSIKA",
    category: "Theater",
    image: "https://picsum.photos/seed/theater/800/600",
    date: "Mar 6, 2025",
    time: "7:00 PM",
    status: "Upcoming",
    organizer: "National Theatre",
    description: "A cultural masterpiece about history and tradition.",
    venue: "National Theatre, Accra",
    ticketTypes: [
      {
        id: "t_std",
        name: "Standard",
        price: 80,
        available: 300,
      },
      {
        id: "t_prem",
        name: "Premium",
        price: 150,
        available: 100,
      },
    ],
  },
  {
    id: "5",
    title: "Miss Uni Ghana 2024",
    eventCode: "MUG24",
    category: "Pageantry",
    image: "https://picsum.photos/seed/pageant/800/600",
    date: "Nov 16, 2024",
    time: "6:00 PM",
    status: "Upcoming",
    organizer: "UniGhana Org",
    description: "Celebrating beauty, intelligence, and leadership.",
    venue: "National Theatre, Accra",
    ticketTypes: [
      {
        id: "t_reg",
        name: "Regular",
        price: 150,
        available: 400,
        description: "General seating",
      },
      {
        id: "t_vip",
        name: "VIP",
        price: 400,
        available: 80,
        description: "Premium seating + refreshments",
      },
    ],
  },
  {
    id: "6",
    title: "Ghana Tech Awards Night",
    eventCode: "GTA24",
    category: "Awards",
    image: "https://picsum.photos/seed/tech/800/600",
    date: "Oct 10, 2024",
    time: "7:00 PM",
    status: "Live",
    organizer: "TechWave Africa",
    description: "Honoring outstanding innovation in Ghana’s tech ecosystem.",
    venue: "Kempinski Hotel Gold Coast City",
    ticketTypes: [
      {
        id: "t_std",
        name: "Standard",
        price: 300,
        available: 200,
        description: "Awards hall access",
      },
      {
        id: "t_vvip",
        name: "VVIP",
        price: 1000,
        available: 30,
        description: "Dinner + backstage access",
      },
    ],
  },
  {
    id: "7",
    title: "Campus Jam Fest",
    eventCode: "CJF24",
    category: "Concert",
    image: "https://picsum.photos/seed/campus/800/600",
    date: "Sep 21, 2024",
    time: "5:00 PM",
    status: "Ended",
    organizer: "Student Groove Network",
    description: "A vibrant music festival for campus creatives.",
    venue: "Legon Sports Complex",
    ticketTypes: [
      {
        id: "t_reg",
        name: "Regular",
        price: 50,
        available: 0,
        description: "Standing access",
      },
      {
        id: "t_vip",
        name: "VIP",
        price: 150,
        available: 0,
        description: "Covered seating",
      },
    ],
  },
  {
    id: "8",
    title: "National Science Fair 2024",
    eventCode: "NSF24",
    category: "School",
    image: "https://picsum.photos/seed/science/800/600",
    date: "Aug 14, 2024",
    time: "9:00 AM",
    status: "Ended",
    organizer: "Ghana Education Service",
    description: "Showcasing innovative student science projects nationwide.",
    venue: "Accra International Conference Centre",
    ticketTypes: [
      {
        id: "t_free",
        name: "Free Entry",
        price: 0,
        available: 1000,
        description: "Open to the public",
      },
    ],
  },
  {
    id: "9",
    title: "Comedy Night with OB Amponsah",
    eventCode: "CNOB24",
    category: "Concert",
    image: "https://picsum.photos/seed/comedy/800/600",
    date: "Nov 2, 2024",
    time: "8:30 PM",
    status: "Upcoming",
    organizer: "LaughLine GH",
    description: "An evening of premium stand-up comedy.",
    venue: "National Theatre, Accra",
    ticketTypes: [
      {
        id: "t_std",
        name: "Standard",
        price: 120,
        available: 300,
        description: "Balcony seating",
      },
      {
        id: "t_vip",
        name: "VIP",
        price: 300,
        available: 60,
        description: "Front seating + drinks",
      },
    ],
  },
  {
    id: "10",
    title: "Senior High Debate Championship",
    eventCode: "SHDC24",
    category: "School",
    image: "https://picsum.photos/seed/debate/800/600",
    date: "Jul 5, 2024",
    time: "10:00 AM",
    status: "Ended",
    organizer: "National Debate Council",
    description: "Top SHS schools compete for national honors.",
    venue: "University of Cape Coast Auditorium",
    ticketTypes: [
      {
        id: "t_std",
        name: "Standard",
        price: 30,
        available: 0,
        description: "Auditorium seating",
      },
    ],
  },
  {
    id: "11",
    title: "Miss Tourism Ghana",
    eventCode: "MTG24",
    category: "Pageantry",
    image: "https://picsum.photos/seed/tourism/800/600",
    date: "Dec 7, 2024",
    time: "7:00 PM",
    status: "Upcoming",
    organizer: "Tourism Authority Ghana",
    description: "Promoting Ghana’s culture and tourism through pageantry.",
    venue: "Fantasy Dome, Trade Fair",
    ticketTypes: [
      {
        id: "t_reg",
        name: "Regular",
        price: 100,
        available: 350,
        description: "Standard seating",
      },
      {
        id: "t_vip",
        name: "VIP",
        price: 350,
        available: 70,
        description: "Close-up seating + souvenir",
      },
    ],
  },
  {
    id: "12",
    title: "Worship & Praise Explosion",
    eventCode: "WPE24",
    category: "Concert",
    image: "https://picsum.photos/seed/worship/800/600",
    date: "Oct 27, 2024",
    time: "4:00 PM",
    status: "Live",
    organizer: "Heaven Sound Ministry",
    description: "A powerful night of praise and worship.",
    venue: "Perez Dome, Dzorwulu",
    ticketTypes: [
      {
        id: "t_free",
        name: "Free Entry",
        price: 0,
        available: 800,
        description: "First come, first serve",
      },
    ],
  },
  {
    id: "13",
    title: "Startup Pitch Fest Accra",
    eventCode: "SPF24",
    category: "Awards",
    image: "https://picsum.photos/seed/startup/800/600",
    date: "Nov 30, 2024",
    time: "1:00 PM",
    status: "Upcoming",
    organizer: "Founders Hub Africa",
    description: "Early-stage startups pitch to investors and mentors.",
    venue: "Impact Hub Accra",
    ticketTypes: [
      {
        id: "t_std",
        name: "Attendee",
        price: 80,
        available: 200,
        description: "Access to pitch sessions",
      },
      {
        id: "t_vip",
        name: "Investor Pass",
        price: 500,
        available: 40,
        description: "VIP seating + networking",
      },
    ],
  },
  {
    id: "14",
    title: "Inter-Hall Sports Awards",
    eventCode: "IHSA24",
    category: "Awards",
    image: "https://picsum.photos/seed/sports/800/600",
    date: "Jun 18, 2024",
    time: "6:30 PM",
    status: "Ended",
    organizer: "University Sports Council",
    description: "Recognizing outstanding inter-hall sports performances.",
    venue: "KNUST Great Hall",
    ticketTypes: [
      {
        id: "t_std",
        name: "Standard",
        price: 40,
        available: 0,
        description: "General hall access",
      },
    ],
  },
];
