import { VotingEvent } from "../types";

export const mockVotingEvents: VotingEvent[] = [
  {
    id: "1",
    title: "Ghana Music Awards 2025",
    eventCode: "GMA25",
    category: "Awards",
    image: "https://picsum.photos/seed/music/800/600",
    date: "Ends in 2 days",
    status: "Live",
    organizer: "Charterhouse Ghana",
    description: "The biggest night in Ghana music celebrating excellence.",
    totalVotes: 154200,
    categories: [
      {
        id: "cat_1",
        name: "Artiste of the Year",
        candidates: [
          {
            id: "cand_1",
            name: "Black Sherif",
            image: "https://picsum.photos/seed/blacko/200/200",
            code: "BS",
            votes: 45000,
          },
          {
            id: "cand_2",
            name: "Sarkodie",
            image: "https://picsum.photos/seed/sark/200/200",
            code: "SK",
            votes: 42000,
          },
          {
            id: "cand_stone",
            name: "Stonebwoy",
            image: "https://picsum.photos/seed/stone/200/200",
            code: "ST",
            votes: 40000,
          },
          {
            id: "cand_shatta",
            name: "Shatta Wale",
            image: "https://picsum.photos/seed/shatta/200/200",
            code: "SW",
            votes: 38000,
          },
        ],
      },
      {
        id: "cat_2",
        name: "New Artiste of the Year",
        candidates: [
          {
            id: "cand_3",
            name: "King Paluta",
            image: "https://picsum.photos/seed/paluta/200/200",
            code: "KP",
            votes: 12000,
          },
          {
            id: "cand_olive",
            name: "OliveTheBoy",
            image: "https://picsum.photos/seed/olive/200/200",
            code: "OB",
            votes: 11000,
          },
        ],
      },
      {
        id: "cat_3",
        name: "Reggae/Dancehall Artiste",
        candidates: [
          {
            id: "rd_1",
            name: "Stonebwoy",
            code: "SB-RD",
            votes: 8500,
            image: "https://picsum.photos/seed/stone/200/200",
          },
          {
            id: "rd_2",
            name: "Samini",
            code: "SM-RD",
            votes: 6200,
            image: "https://picsum.photos/seed/samini/200/200",
          },
          {
            id: "rd_3",
            name: "Ras Kuuku",
            code: "RK-RD",
            votes: 4100,
            image: "https://picsum.photos/seed/ras/200/200",
          },
        ],
      },
      {
        id: "cat_4",
        name: "Highlife Artiste of the Year",
        candidates: [
          {
            id: "hl_1",
            name: "Kofi Kinaata",
            code: "KK-HL",
            votes: 9800,
            image: "https://picsum.photos/seed/kinaata/200/200",
          },
          {
            id: "hl_2",
            name: "Kuami Eugene",
            code: "KE-HL",
            votes: 9200,
            image: "https://picsum.photos/seed/eugene/200/200",
          },
          {
            id: "hl_3",
            name: "Akwaboah",
            code: "AK-HL",
            votes: 7500,
            image: "https://picsum.photos/seed/akwaboah/200/200",
          },
        ],
      },
      {
        id: "cat_5",
        name: "Hiplife/Hiphop Artiste",
        candidates: [
          {
            id: "hh_1",
            name: "Sarkodie",
            code: "SK-HH",
            votes: 15400,
            image: "https://picsum.photos/seed/sark/200/200",
          },
          {
            id: "hh_2",
            name: "Black Sherif",
            code: "BS-HH",
            votes: 16200,
            image: "https://picsum.photos/seed/blacko/200/200",
          },
          {
            id: "hh_3",
            name: "Amerado",
            code: "AM-HH",
            votes: 9500,
            image: "https://picsum.photos/seed/amerado/200/200",
          },
        ],
      },
      {
        id: "cat_6",
        name: "Afrobeats Artiste of the Year",
        candidates: [
          {
            id: "ab_1",
            name: "King Promise",
            code: "KP-AB",
            votes: 14500,
            image: "https://picsum.photos/seed/promise/200/200",
          },
          {
            id: "ab_2",
            name: "KiDi",
            code: "KD-AB",
            votes: 11200,
            image: "https://picsum.photos/seed/kidi/200/200",
          },
          {
            id: "ab_3",
            name: "Camidoh",
            code: "CM-AB",
            votes: 8900,
            image: "https://picsum.photos/seed/camidoh/200/200",
          },
        ],
      },
      {
        id: "cat_7",
        name: "Gospel Artiste of the Year",
        candidates: [
          {
            id: "gp_1",
            name: "Diana Hamilton",
            code: "DH-GP",
            votes: 18000,
            image: "https://picsum.photos/seed/diana/200/200",
          },
          {
            id: "gp_2",
            name: "Joe Mettle",
            code: "JM-GP",
            votes: 17500,
            image: "https://picsum.photos/seed/joe/200/200",
          },
          {
            id: "gp_3",
            name: "Piesie Esther",
            code: "PE-GP",
            votes: 16800,
            image: "https://picsum.photos/seed/piesie/200/200",
          },
          {
            id: "gp_4",
            name: "Nacee",
            code: "NC-GP",
            votes: 15900,
            image: "https://picsum.photos/seed/nacee/200/200",
          },
        ],
      },
      {
        id: "cat_8",
        name: "Female Vocalist of the Year",
        candidates: [
          {
            id: "fv_1",
            name: "Adina Thembi",
            code: "AD-FV",
            votes: 5600,
            image: "https://picsum.photos/seed/adina/200/200",
          },
          {
            id: "fv_2",
            name: "Gyakie",
            code: "GK-FV",
            votes: 7200,
            image: "https://picsum.photos/seed/gyakie/200/200",
          },
          {
            id: "fv_3",
            name: "Sista Afia",
            code: "SA-FV",
            votes: 4300,
            image: "https://picsum.photos/seed/sista/200/200",
          },
        ],
      },
      {
        id: "cat_9",
        name: "Male Vocalist of the Year",
        candidates: [
          {
            id: "mv_1",
            name: "Kyei Mensah",
            code: "KM-MV",
            votes: 3400,
            image: "https://picsum.photos/seed/kyei/200/200",
          },
          {
            id: "mv_2",
            name: "Perez Musik",
            code: "PM-MV",
            votes: 4100,
            image: "https://picsum.photos/seed/perez/200/200",
          },
          {
            id: "mv_3",
            name: "Camidoh",
            code: "CM-MV",
            votes: 5800,
            image: "https://picsum.photos/seed/camidoh/200/200",
          },
        ],
      },
      {
        id: "cat_10",
        name: "Best Rapper of the Year",
        candidates: [
          {
            id: "rp_1",
            name: "Strongman",
            code: "SM-RP",
            votes: 8900,
            image: "https://picsum.photos/seed/strong/200/200",
          },
          {
            id: "rp_2",
            name: "Medikal",
            code: "MD-RP",
            votes: 9400,
            image: "https://picsum.photos/seed/medikal/200/200",
          },
          {
            id: "rp_3",
            name: "Eno Barony",
            code: "EB-RP",
            votes: 7600,
            image: "https://picsum.photos/seed/eno/200/200",
          },
          {
            id: "rp_4",
            name: "Teephlow",
            code: "TP-RP",
            votes: 5200,
            image: "https://picsum.photos/seed/tee/200/200",
          },
        ],
      },
      {
        id: "cat_11",
        name: "Songwriter of the Year",
        candidates: [
          {
            id: "sw_1",
            name: "Kofi Kinaata - Effiakuma",
            code: "KK-SW",
            votes: 4500,
            image: "https://picsum.photos/seed/kinaata/200/200",
          },
          {
            id: "sw_2",
            name: "Piesie Esther - Waye Me Yie",
            code: "PE-SW",
            votes: 5500,
            image: "https://picsum.photos/seed/piesie/200/200",
          },
          {
            id: "sw_3",
            name: "Black Sherif - Oh Paradise",
            code: "BS-SW",
            votes: 6100,
            image: "https://picsum.photos/seed/blacko/200/200",
          },
        ],
      },
      {
        id: "cat_12",
        name: "Best Collaboration",
        candidates: [
          {
            id: "col_1",
            name: "Liquor - Mawuli Younggod ft. Medikal",
            code: "LQ-CL",
            votes: 3200,
            image: "https://picsum.photos/seed/mawuli/200/200",
          },
          {
            id: "col_2",
            name: "Terminator - King Promise ft. Youg Jonn",
            code: "TM-CL",
            votes: 12000,
            image: "https://picsum.photos/seed/promise/200/200",
          },
          {
            id: "col_3",
            name: "Otan - Sarkodie",
            code: "OT-CL",
            votes: 8700,
            image: "https://picsum.photos/seed/sark/200/200",
          },
        ],
      },
      {
        id: "cat_13",
        name: "Best Music Video",
        candidates: [
          {
            id: "vid_1",
            name: "Oil in my Head - Black Sherif",
            code: "OH-VD",
            votes: 9800,
            image: "https://picsum.photos/seed/blacko/200/200",
          },
          {
            id: "vid_2",
            name: "Cryptocurrency - Kuami Eugene",
            code: "CY-VD",
            votes: 7600,
            image: "https://picsum.photos/seed/eugene/200/200",
          },
          {
            id: "vid_3",
            name: "10AM - Strongman",
            code: "TM-VD",
            votes: 5400,
            image: "https://picsum.photos/seed/strong/200/200",
          },
        ],
      },
      {
        id: "cat_14",
        name: "Album of the Year",
        candidates: [
          {
            id: "alb_1",
            name: "The Villain I Never Was - Black Sherif",
            code: "VN-AL",
            votes: 15600,
            image: "https://picsum.photos/seed/blacko/200/200",
          },
          {
            id: "alb_2",
            name: "Jamz - Sarkodie",
            code: "JZ-AL",
            votes: 14200,
            image: "https://picsum.photos/seed/sark/200/200",
          },
          {
            id: "alb_3",
            name: "5th Dimension - Stonebwoy",
            code: "FD-AL",
            votes: 13800,
            image: "https://picsum.photos/seed/stone/200/200",
          },
        ],
      },
      {
        id: "cat_15",
        name: "EP of the Year",
        candidates: [
          {
            id: "ep_1",
            name: "Truths & Rumors - Amerado",
            code: "TR-EP",
            votes: 4200,
            image: "https://picsum.photos/seed/amerado/200/200",
          },
          {
            id: "ep_2",
            name: "Mood Swings - Edem",
            code: "MS-EP",
            votes: 3100,
            image: "https://picsum.photos/seed/edem/200/200",
          },
          {
            id: "ep_3",
            name: "Avana - Gyakie",
            code: "AV-EP",
            votes: 6500,
            image: "https://picsum.photos/seed/gyakie/200/200",
          },
        ],
      },
      {
        id: "cat_16",
        name: "Record of the Year",
        candidates: [
          {
            id: "rec_1",
            name: "Far Away - Sarkodie",
            code: "FA-RC",
            votes: 5300,
            image: "https://picsum.photos/seed/sark/200/200",
          },
          {
            id: "rec_2",
            name: "Maniod - Stonebwoy",
            code: "MN-RC",
            votes: 5100,
            image: "https://picsum.photos/seed/stone/200/200",
          },
          {
            id: "rec_3",
            name: "Soja - Black Sherif",
            code: "SJ-RC",
            votes: 5900,
            image: "https://picsum.photos/seed/blacko/200/200",
          },
        ],
      },
      {
        id: "cat_17",
        name: "Audio Engineer of the Year",
        candidates: [
          {
            id: "ae_1",
            name: "Possigee",
            code: "PS-AE",
            votes: 2000,
            image: "https://picsum.photos/seed/possigee/200/200",
          },
          {
            id: "ae_2",
            name: "MOG Beatz",
            code: "MG-AE",
            votes: 2500,
            image: "https://picsum.photos/seed/mog/200/200",
          },
          {
            id: "ae_3",
            name: "Streetbeatz",
            code: "SB-AE",
            votes: 1800,
            image: "https://picsum.photos/seed/street/200/200",
          },
        ],
      },
      {
        id: "cat_18",
        name: "Producer of the Year",
        candidates: [
          {
            id: "pd_1",
            name: "MOG Beatz",
            code: "MG-PD",
            votes: 6700,
            image: "https://picsum.photos/seed/mog/200/200",
          },
          {
            id: "pd_2",
            name: "Samsney",
            code: "SM-PD",
            votes: 5400,
            image: "https://picsum.photos/seed/samsney/200/200",
          },
          {
            id: "pd_3",
            name: "Atown TSB",
            code: "AT-PD",
            votes: 4900,
            image: "https://picsum.photos/seed/atown/200/200",
          },
        ],
      },
      {
        id: "cat_19",
        name: "Best Group",
        candidates: [
          {
            id: "bg_1",
            name: "R2Bees",
            code: "RB-BG",
            votes: 8500,
            image: "https://picsum.photos/seed/r2bees/200/200",
          },
          {
            id: "bg_2",
            name: "Keche",
            code: "KC-BG",
            votes: 6200,
            image: "https://picsum.photos/seed/keche/200/200",
          },
          {
            id: "bg_3",
            name: "DopeNation",
            code: "DN-BG",
            votes: 7100,
            image: "https://picsum.photos/seed/dope/200/200",
          },
        ],
      },
      {
        id: "cat_20",
        name: "African Artiste of the Year",
        candidates: [
          {
            id: "aa_1",
            name: "Burna Boy",
            code: "BB-AA",
            votes: 25000,
            image: "https://picsum.photos/seed/burna/200/200",
          },
          {
            id: "aa_2",
            name: "Davido",
            code: "DV-AA",
            votes: 24500,
            image: "https://picsum.photos/seed/davido/200/200",
          },
          {
            id: "aa_3",
            name: "Rema",
            code: "RM-AA",
            votes: 21000,
            image: "https://picsum.photos/seed/rema/200/200",
          },
          {
            id: "aa_4",
            name: "Asake",
            code: "AS-AA",
            votes: 20500,
            image: "https://picsum.photos/seed/asake/200/200",
          },
        ],
      },
      {
        id: "cat_21",
        name: "Unsung Artiste",
        candidates: [
          {
            id: "us_1",
            name: "Lali X Lola",
            code: "LX-US",
            votes: 2100,
            image: "https://picsum.photos/seed/lali/200/200",
          },
          {
            id: "us_2",
            name: "Kweku Boateng",
            code: "KB-US",
            votes: 1500,
            image: "https://picsum.photos/seed/kweku/200/200",
          },
          {
            id: "us_3",
            name: "Maya Blu",
            code: "MB-US",
            votes: 2800,
            image: "https://picsum.photos/seed/maya/200/200",
          },
        ],
      },
    ],
  },
  {
    id: "2",
    title: "Legon SRC Election 2024",
    eventCode: "UGSRC",
    category: "School",
    image: "https://picsum.photos/seed/legon/800/600",
    date: "Ends at 5 PM",
    status: "Live",
    organizer: "University of Ghana Electoral Commission",
    description:
      "Deciding the next SRC President for the 2024/2025 academic year.",
    totalVotes: 12500,
    categories: [
      {
        id: "cat_sec",
        name: "General Secretary",
        candidates: [
          {
            id: "cand_sec_1",
            name: "Adwoa Smart",
            image: "https://picsum.photos/seed/adwoa/200/200",
            code: "AS",
            votes: 5000,
          },
        ],
      },
    ],
  },
  {
    id: "3",
    title: "Miss Ghana 2025",
    eventCode: "MSGHA",
    category: "Pageantry",
    image: "https://picsum.photos/seed/pageant/800/600",
    date: "Starts in 5 days",
    status: "Upcoming",
    organizer: "Exclusive Events Ghana",
    description:
      "Who wears the crown next? Vote for your favorite beauty queen.",
    totalVotes: 0,
    categories: [
      {
        id: "cat_miss_1",
        name: "Viewer's Choice",
        candidates: [
          {
            id: "cand_miss_1",
            name: "Naa Okailey",
            image: "https://picsum.photos/seed/naa/200/200",
            code: "NO",
            votes: 0,
          },
          {
            id: "cand_miss_2",
            name: "Afia Pokua",
            image: "https://picsum.photos/seed/afia/200/200",
            code: "AP",
            votes: 0,
          },
        ],
      },
    ],
  },
  {
    id: "4",
    title: "GPL Player of the Month",
    eventCode: "GPL-OCT",
    category: "Sports",
    image: "https://picsum.photos/seed/football/800/600",
    date: "Ends in 24 hours",
    status: "Live",
    organizer: "Ghana Football Association",
    description:
      "Vote for the outstanding player in the Ghana Premier League for October.",
    totalVotes: 8900,
    categories: [
      {
        id: "cat_gpl_1",
        name: "Best Forward",
        candidates: [
          {
            id: "cand_gpl_1",
            name: "Steven Mukwala",
            image: "https://picsum.photos/seed/mukwala/200/200",
            code: "SM",
            votes: 3200,
          },
          {
            id: "cand_gpl_2",
            name: "Richmond Lamptey",
            image: "https://picsum.photos/seed/lamptey/200/200",
            code: "RL",
            votes: 2800,
          },
        ],
      },
    ],
  },
  {
    id: "5",
    title: "Ghana Startup Awards",
    eventCode: "GSA25",
    category: "Tech",
    image: "https://picsum.photos/seed/tech/800/600",
    date: "Ended yesterday",
    status: "Ended",
    organizer: "Ghana Tech Network",
    description: "Recognizing the most innovative startups in the ecosystem.",
    totalVotes: 45000,
    categories: [
      {
        id: "cat_tech_1",
        name: "Fintech of the Year",
        candidates: [
          {
            id: "cand_tech_1",
            name: "Zeepay",
            image: "https://picsum.photos/seed/zeepay/200/200",
            code: "ZP",
            votes: 15000,
          },
          {
            id: "cand_tech_2",
            name: "Hubtel",
            image: "https://picsum.photos/seed/hubtel/200/200",
            code: "HB",
            votes: 14500,
          },
        ],
      },
    ],
  },
  {
    id: "6",
    title: "KNUST SRC Elections",
    eventCode: "KNUST-SRC",
    category: "School",
    image: "https://picsum.photos/seed/knust/800/600",
    date: "Live Now",
    status: "Live",
    organizer: "KNUST Electoral Commission",
    description: "Vote for your leaders. Teknocrat, your voice matters!",
    totalVotes: 22000,
    categories: [
      {
        id: "cat_pres_knust",
        name: "SRC President",
        candidates: [
          {
            id: "cand_knust_1",
            name: "Master Oten",
            image: "https://picsum.photos/seed/oten/200/200",
            code: "MO",
            votes: 8000,
          },
          {
            id: "cand_knust_2",
            name: "Yvonne Nti",
            image: "https://picsum.photos/seed/yvonne/200/200",
            code: "YN",
            votes: 7500,
          },
        ],
      },
    ],
  },
  {
    id: "7",
    title: "National Gospel Excellence Awards",
    eventCode: "NGEA",
    category: "Awards",
    image: "https://picsum.photos/seed/gospel/800/600",
    date: "Ends in 1 week",
    status: "Live",
    organizer: "Christian Council",
    description: "Honoring the best in ministry and gospel music.",
    totalVotes: 67000,
    categories: [
      {
        id: "cat_gospel_1",
        name: "Song of the Year",
        candidates: [
          {
            id: "cand_gospel_1",
            name: "Diana Hamilton",
            image: "https://picsum.photos/seed/diana/200/200",
            code: "DH",
            votes: 30000,
          },
          {
            id: "cand_gospel_2",
            name: "Joe Mettle",
            image: "https://picsum.photos/seed/joe/200/200",
            code: "JM",
            votes: 28000,
          },
        ],
      },
    ],
  },
  {
    id: "8",
    title: "Accra Food Festival: Best Vendor",
    eventCode: "AFF-25",
    category: "Lifestyle",
    image: "https://picsum.photos/seed/food/800/600",
    date: "Starts Tomorrow",
    status: "Upcoming",
    organizer: "Accra Expat Life",
    description: "Who makes the best Jollof in the city? Come taste and vote!",
    totalVotes: 0,
    categories: [
      {
        id: "cat_food_1",
        name: "Best Jollof Vendor",
        candidates: [
          {
            id: "cand_food_1",
            name: "Menufinder Jollof",
            image: "https://picsum.photos/seed/menu/200/200",
            code: "MJ",
            votes: 0,
          },
          {
            id: "cand_food_2",
            name: "Sister Akos Special",
            image: "https://picsum.photos/seed/akos/200/200",
            code: "SA",
            votes: 0,
          },
        ],
      },
    ],
  },
  {
    id: "9",
    title: "NSMQ Fan Favourite 2025",
    eventCode: "NSMQ-FAN",
    category: "Education",
    image: "https://picsum.photos/seed/science/800/600",
    date: "Live",
    status: "Live",
    organizer: "Primetime Limited",
    description:
      "Vote for the most spirited school in this year's competition.",
    totalVotes: 340000,
    categories: [
      {
        id: "cat_nsmq_1",
        name: "School of the Year",
        candidates: [
          {
            id: "cand_nsmq_1",
            name: "PRESEC Legon",
            image: "https://picsum.photos/seed/presec/200/200",
            code: "PS",
            votes: 120000,
          },
          {
            id: "cand_nsmq_2",
            name: "Prempeh College",
            image: "https://picsum.photos/seed/prempeh/200/200",
            code: "PC",
            votes: 110000,
          },
          {
            id: "cand_nsmq_3",
            name: "Adisadel College",
            image: "https://picsum.photos/seed/adisco/200/200",
            code: "AC",
            votes: 95000,
          },
        ],
      },
    ],
  },
  {
    id: "10",
    title: "CIMG Marketing Awards",
    eventCode: "CIMG-24",
    category: "Corporate",
    image: "https://picsum.photos/seed/corporate/800/600",
    date: "Ended",
    status: "Ended",
    organizer: "Chartered Institute of Marketing Ghana",
    description: "Celebrating marketing excellence in the corporate world.",
    totalVotes: 5000,
    categories: [
      {
        id: "cat_cimg_1",
        name: "Marketing Woman of the Year",
        candidates: [
          {
            id: "cand_cimg_1",
            name: "Patricia Obo-Nai",
            image: "https://picsum.photos/seed/patricia/200/200",
            code: "PN",
            votes: 2100,
          },
          {
            id: "cand_cimg_2",
            name: "Abena Osei-Poku",
            image: "https://picsum.photos/seed/abena/200/200",
            code: "AO",
            votes: 1900,
          },
        ],
      },
    ],
  },
];
